In [62]:
import pandas as pd
data= pd.read_csv("archive\IPL_Matches_2008_2022.csv")
data.head()

ID       City        Date Season  MatchNumber  \
0  1312200  Ahmedabad  2022-05-29   2022        Final   
1  1312199  Ahmedabad  2022-05-27   2022  Qualifier 2   
2  1312198    Kolkata  2022-05-25   2022   Eliminator   
3  1312197    Kolkata  2022-05-24   2022  Qualifier 1   
4  1304116     Mumbai  2022-05-22   2022           70   

                         Team1                 Team2  \
0             Rajasthan Royals        Gujarat Titans   
1  Royal Challengers Bangalore      Rajasthan Royals   
2  Royal Challengers Bangalore  Lucknow Super Giants   
3             Rajasthan Royals        Gujarat Titans   
4          Sunrisers Hyderabad          Punjab Kings   

                              Venue            TossWinner TossDecision  \
0  Narendra Modi Stadium, Ahmedabad      Rajasthan Royals          bat   
1  Narendra Modi Stadium, Ahmedabad      Rajasthan Royals        field   
2             Eden Gardens, Kolkata  Lucknow Super Giants        field   
3             Eden Gardens, Kolkata        Gujarat Titans        field   
4          Wankhede Stadium, Mumbai   Sunrisers Hyderabad          bat   

  SuperOver                  WinningTeam    WonBy  Margin method  \
0         N               Gujarat Titans  Wickets     7.0    NaN   
1         N             Rajasthan Royals  Wickets     7.0    NaN   
2         N  Royal Challengers Bangalore     Runs    14.0    NaN   
3         N               Gujarat Titans  Wickets     7.0    NaN   
4         N                 Punjab Kings  Wickets     5.0    NaN   

  Player_of_Match                                       Team1Players  \
0       HH Pandya  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...   
1      JC Buttler  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...   
2      RM Patidar  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...   
3       DA Miller  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...   
4   Harpreet Brar  ['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...   

                                        Team2Players        Umpire1  \
0  ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...    CB Gaffaney   
1  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...    CB Gaffaney   
2  ['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...  J Madanagopal   
3  ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...   BNJ Oxenford   
4  ['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...   AK Chaudhary   

         Umpire2  
0    Nitin Menon  
1    Nitin Menon  
2       MA Gough  
3      VK Sharma  
4  NA Patwardhan

In [83]:

columns_to_keep = ['Team1', 'Team2', 'TossWinner', 'TossDecision', 'WinningTeam']
data = data[columns_to_keep]


In [84]:
data.head()

Team1  Team2  TossWinner  TossDecision  WinningTeam
0     13      5          13             0            5
1     16     13          13             1           13
2     16      9           9             1           16
3     13      5           5             1            5
4     17     12          17             0           12

In [85]:
data.isnull().sum()

Team1           0
Team2           0
TossWinner      0
TossDecision    0
WinningTeam     0
dtype: int64

In [66]:
data.fillna("n/r",inplace=True)

In [67]:
data.WinningTeam.unique()

array(['Gujarat Titans', 'Rajasthan Royals',
       'Royal Challengers Bangalore', 'Punjab Kings', 'Mumbai Indians',
       'Lucknow Super Giants', 'Sunrisers Hyderabad', 'Delhi Capitals',
       'Kolkata Knight Riders', 'Chennai Super Kings', 'Kings XI Punjab',
       'n/r', 'Delhi Daredevils', 'Rising Pune Supergiant',
       'Gujarat Lions', 'Rising Pune Supergiants', 'Pune Warriors',
       'Deccan Chargers', 'Kochi Tuskers Kerala'], dtype=object)

In [68]:
data.columns

Index(['Team1', 'Team2', 'TossWinner', 'TossDecision', 'WinningTeam'], dtype='object')

In [69]:
from sklearn.preprocessing import LabelEncoder

le_team1 = LabelEncoder()
data['Team1'] = le_team1.fit_transform(data['Team1'])
data['Team1'].unique()

array([13, 16, 17,  2,  0,  5,  9,  8, 12, 10,  6,  3, 14,  4, 15, 11,  1,
        7])

In [70]:
# label_encoder = LabelEncoder()

le_team2 = LabelEncoder()
data['Team2'] = le_team2.fit_transform(data['Team2'])
data['Team2'].unique()

array([ 5, 13,  9, 12, 10, 16,  8, 17,  2,  0,  6,  3, 14,  4, 15, 11,  1,
        7])

In [71]:
# label_encoder = LabelEncoder()

le_TossWinner = LabelEncoder()
data['TossWinner'] = le_TossWinner.fit_transform(data['TossWinner'])
data['TossWinner'].unique()

array([13,  9,  5, 17, 10,  0, 12,  8, 16,  2,  6,  3, 14,  4, 15, 11,  1,
        7])

In [72]:
le_TossDecision = LabelEncoder()
data['TossDecision'] = le_TossDecision.fit_transform(data['TossDecision'])
data['TossDecision'].unique()

array([0, 1])

In [73]:
le_WinningTeam = LabelEncoder()
data['WinningTeam'] = le_WinningTeam.fit_transform(data['WinningTeam'])
data['WinningTeam'].unique()

array([ 5, 13, 16, 12, 10,  9, 17,  2,  8,  0,  6, 18,  3, 14,  4, 15, 11,
        1,  7])

In [74]:

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np


In [75]:
#splitting the data into trainning and testing datasets
X = data.drop('WinningTeam', axis=1)
y = data['WinningTeam']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42
                                                    )


In [76]:
model = LogisticRegression()
# Train the model on the training data
# Train the model on the training data
model.fit(X_train, y_train)
# Predict the target variable for the test data
y_pred = model.predict(X_test)


c:\Users\panic\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [79]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: ", accuracy)


Accuracy:  0.21578947368421053


In [ ]:
#Random Forest

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Assuming your DataFrame is named 'ipl_data_encoded'
# Separate the features (X) and the target variable (y)
X = data.drop('WinningTeam', axis=1)
y = data['WinningTeam']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the Random Forest classifier
rf_classifier = RandomForestClassifier(random_state=42,n_estimators = 50)

# Train the model on the training data
rf_classifier.fit(X_train, y_train)

# Make predictions on the test data
y_pred = rf_classifier.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# print("\nClassification Report:")
# print(classification_report(y_test, y_pred))

# print("\nConfusion Matrix:")
# print(confusion_matrix(y_test, y_pred))


Accuracy: 0.5157894736842106


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
import xgboost as xgb
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Assuming your DataFrame is named 'ipl_data_encoded'

# Separate the features (X) and the target variable (y)
X = data.drop('WinningTeam', axis=1)
y = data['WinningTeam']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the XGBoost model
xgb_model = xgb.XGBClassifier(random_state=42,learning_rate = 0.1, max_depth= 2, n_estimators= 150)

# Train the model on the training data
xgb_model.fit(X_train, y_train)

# Make predictions on the test data
y_pred = xgb_model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# print("\nClassification Report:")
# print(classification_report(y_test, y_pred))

# print("\nConfusion Matrix:")
# print(confusion_matrix(y_test, y_pred))


Accuracy: 0.5210526315789473


In [ ]:
#SVM

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Assuming your DataFrame is named 'ipl_data_encoded'

# Separate the features (X) and the target variable (y)
X = data.drop('WinningTeam', axis=1)
y = data['WinningTeam']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the SVM model
svm_model = SVC(random_state=42)

# Train the model on the training data
svm_model.fit(X_train, y_train)

# Make predictions on the test data
y_pred = svm_model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# print("\nClassification Report:")
# print(classification_report(y_test, y_pred))

# print("\nConfusion Matrix:")
# print(confusion_matrix(y_test, y_pred))


Accuracy: 0.3157894736842105


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
import xgboost as xgb

# Assuming your DataFrame is named 'ipl_data_encoded'
X = data.drop('WinningTeam', axis=1)
y = data['WinningTeam']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the hyperparameter grid
param_grid = {
    'learning_rate': [0.01, 0.1, 0.2],
    # 'n_estimators': [100,50,200,150],
    'max_depth': [None,1,3,2]
}

# Initialize the XGBoost model
xgb_model = xgb.XGBClassifier(random_state=42)

# Initialize GridSearchCV with the model and hyperparameter grid
grid_search = GridSearchCV(estimator=xgb_model, param_grid=param_grid, scoring='accuracy', cv=3)

# Perform grid search with cross-validation
grid_search.fit(X_train, y_train)

# Get the best hyperparameters and model
best_params = grid_search.best_params_
best_model = grid_search.best_estimator_

# Evaluate the best model on the test set
y_pred = best_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Best Hyperparameters:", best_params)
print("Best Model Accuracy:", accuracy)


Best Hyperparameters: {'learning_rate': 0.1, 'max_depth': 2}
Best Model Accuracy: 0.531578947368421


In [ ]:
# from sklearn.metrics import mean_squared_error,mean_absolute_error
# error = np.sqrt(mean_squared_error(y_test,y_pred))
# error

In [ ]:
X

Team1  Team2  TossWinner  TossDecision
0       13      5          13             0
1       16     13          13             1
2       16      9           9             1
3       13      5           5             1
4       17     12          17             0
..     ...    ...         ...           ...
945      8      1           1             0
946     10     16          10             0
947      3     13          13             0
948      6      0           0             0
949     16      8          16             1

[950 rows x 4 columns]

In [ ]:
data

Team1  Team2  TossWinner  TossDecision  WinningTeam
0       13      5          13             0            5
1       16     13          13             1           13
2       16      9           9             1           16
3       13      5           5             1            5
4       17     12          17             0           12
..     ...    ...         ...           ...          ...
945      8      1           1             0            8
946     10     16          10             0           16
947      3     13          13             0            3
948      6      0           0             0            0
949     16      8          16             1            8

[950 rows x 5 columns]

In [ ]:
X = np.array([['Rajasthan Royals','Gujarat Titans','Rajasthan Royals', 'field']])
X

array([['Rajasthan Royals', 'Gujarat Titans', 'Rajasthan Royals',
        'field']], dtype='<U16')

In [ ]:
X[:, 0] = le_team1.transform(X[:,0])
X[:, 1] = le_team2.transform(X[:,1])
X[:, 2] = le_TossWinner.transform(X[:,2])
X[:, 3] = le_TossDecision.transform(X[:,3])
X = X.astype(float)
X

array([[13.,  5., 13.,  1.]])

In [ ]:
y_pred = best_model.predict(X)
y_pred

array([5], dtype=int64)

In [ ]:
y_pred_encoded = best_model.predict(X)

# Inverse transform the label-encoded predictions to get categorical values
y_pred_categorical = le_WinningTeam.inverse_transform(y_pred_encoded)
y_pred_categorical

predicted_team = y_pred_categorical[0]

print(predicted_team)

Gujarat Titans


In [ ]:
import pickle

In [ ]:
data = {"model": best_model, "le_team1":le_team1 , "le_team2": le_team2,"le_TossWinner": le_TossWinner,"le_TossDecision":le_TossDecision}
with open('ipl_saved.pkl', 'wb') as file:
    pickle.dump(data, file)

In [ ]:
with open('ipl_saved.pkl', 'rb') as file:
    data = pickle.load(file)

best_model_model = data["model"]
le_team1 = data["le_team1"]
le_team2 = data["le_team2"]
le_TossWinner = data["le_TossWinner"]
le_TossDecision = data["le_TossDecision"]

In [ ]:
y_pred = best_model_model.predict(X)
y_pred

array([5], dtype=int64)